public class Data2026 {
    public static String[][] getRunners() {
        return new String[][] {
                {"ARWEILER Klaus", "0:48:47"},
                {"HÜLLER Sebastian", "0:34:14"},
                {"MANKE Maik", "0:50:48"},
                {"PFISTER Jens", "0:50:18"},
                {"BÖTSCH Christina", "0:58:29"},
                {"BRUX Tobias", "0:38:08"},
                {"PÖHLER Simone", "1:01:16"},
                {"PLUME Monika", "0:46:33"},
                {"LUKOSCHEK Kester", "0:53:24"},
                {"ANTON Eduard", "0:48:55"},
                {"REICHERT Johannes", "0:57:41"},
                {"SCHMÄLING Uwe", "0:38:12"},
                {"KRIESTER Uwe", "0:37:37"},
                {"SCHULZE Karsten", "0:47:28"},
                {"KORR Christopher", "1:03:52"},
                {"HEROLD-STARSICHOVÁ Martina", "0:44:43"},
                {"DRESCHER Felix", "0:44:48"},
                {"MERGET Paul", "0:47:38"},
                {"MANSKE Julian", "0:35:56"},
                {"STEIGERWALD Christian", "0:54:40"},
                {"HILPERT Saskia", "1:11:20"},
                {"HILPERT Alexander", "0:56:04"},
                {"FREITAG Matthias", "0:59:11"},
                {"HEINZ Anton", "0:57:40"},
                {"PANHANS Robin", "0:54:41"},
                {"KÖLBL Benjamin", "0:57:15"},
                {"MARX Julian", "0:41:06"},
                {"KPOKPOYA Regis", "0:58:53"},
                {"KRIENKE Yvonne", ""},
                {"KELLER Nathalie", "1:03:44"},
                {"STUMPF Alexander", "0:48:44"},
                {"INDERWIES Steffen", "1:08:22"},
                {"DELLERMANN Daniela", "0:38:39"},
                {"KUBOWICZ Arne", "1:03:23"},
        };
    }
}
